# Generated by Django 5.2.3 on 2025-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.IntegerField(default=10),
        ),
    ]
